### ISSUE TITLE
Does not work in the new "Feeds (Most Recent)" section of Facebook.

### ISSUE THREAD

**Issue by AmbientPlatypus** [mrinc/FB-Hide-Recommendations-and-Reels#40]
Facebook has changed its site (yet again), and the Most Recent section, organized by, well, most recent posts, has moved to a new page that loads. Reels, etc. show up on this page, and the Extension fails with an error. I was also unable to send the diagnostic data, so it prompted me to log an issue this way.

**Comment by mrinc** [comment]
@AmbientPlatypus could you send a screen shot of what you mean?

FB changing things does make it annoying -_- haha

**Comment by AmbientPlatypus** [comment]
Thankfully, when I went to duplicate the issue today, it was able to create the diagnostic. You'll see it as #42

**Comment by mrinc** [comment]
Internal reference: Diag data deleted from server
