### ISSUE TITLE
Unable to find the feed elements - extension doesn't work.

### ISSUE THREAD

**Issue by 1019-h** [mrinc/FB-Hide-Recommendations-and-Reels#57]
Hi !

I just downloaded the extension, but it is unable to find the feed elements on my timeline. I tried to send the data, but it kept on "gathering data" for a long time and I think it didn't work.

I have Facebook in french, I'm on Windows 10 (Version 21H2 (Build 19044.2846)) and on Vivaldi (5.6.2867.62) (Chromium browser). Here's a screenshot of the console :
![image](https://github.com/mrinc/FB-Hide-Recommendations-and-Reels/assets/39690366/2131f55f-2db0-448c-abd0-068add56fded)

Thank you.

**Comment by mrinc** [comment]
@1019-h - I have pushed a fix for you :)   
https://github.com/mrinc/FB-Hide-Recommendations-and-Reels/releases/tag/v1.26.26

**Comment by mrinc** [comment]
@1019-h - let me know if that didn't work? (1.27 should have been pushed already)

**Comment by 1019-h** [comment]
> @1019-h - let me know if that didn't work? (1.27 should have been pushed already)

Hi !
It sadly doesn't work either. Here's a screenshot of the console :
![image](https://github.com/mrinc/FB-Hide-Recommendations-and-Reels/assets/39690366/3e472b8a-d8f3-41e4-b846-33255e05ff0d)
I still have : 
- sponsored posts,
- suggested posts,
- suggested groups
It works for hiding "create a new post" block, stories etc, but not for the posts I think...?

**Comment by mrinc** [comment]
okay great!

so its working now.  

basically we search for keys in the ui for certain things to remove/hide.  
since my lang is en by default and although i can change langs to test, i dont always see some of the other post keys in order to add them.  

have a look at the things we search for and let me know if you see them, what they are in fr: https://github.com/mrinc/FB-Hide-Recommendations-and-Reels/blob/master/src/lib/langs.ts#L82.  

then i can add them and push an update for you :)

**Comment by 1019-h** [comment]
Hi ! Sorry for the late answer.

So, after scrolling for some time, I found those to add (based on what you did in the english part) : 

`_suggested: "Suggestions",
_ad: "Sponsorisé",`

But also, those are just missing it seems (even from english) : 

`suggestedGroup: "Groupes suggérés",
suggestedEvent: "Évènements suggérés"`

The first suggests groups we could have interest in, the second events.

I would add also that I don't have that much friends on Facebook and most of them are inactive. So I don't have the posts with "friend commented on this", "friend answered this question" so I can't tell for sure that that would do the job, but it sure would purge my timeline for good. Thanks for this amazing extension and your time and quick answers ♥

**Comment by mrinc** [comment]
@1019-h - please test with changes: https://github.com/mrinc/FB-Hide-Recommendations-and-Reels/releases/tag/v1.26.27-rc0
